name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macosx15.0

    steps:
    - uses: actions/checkout@v4
    - name: Install Bundle
      run: bundle install
    - name: Run unit tests
      run: bundle exec fastlane run_unit_tests --verbose
